let lasina_box = document.getElementById("lasina");
let every_juniko_p = document.getElementsByClassName("juniko");

const juniko_list = {
	"a": `ḽ	Ḭ	á	-a	aͥ	α̍	a	ⵒ`,
	"akesi": `Ӫ	ꗵ	𖠃	ੳ	-0-	.8.	ʘ̈	O:`,
	"ala": `X	☓	╳	✕	×`,
	"alasa": `Ð	⭄	D->	⨮	D ⦈	D-`,
	"ale": `∞	oo	ᨖ	8`,
	"anpa": `Џ	Ụ	⨪	-.-	↓͡↓`,
	"ante": `⩆	ᳲ	≍	\\^/	ꇤ	ʌ̌	><	❭❬	И`,
	"anu": `Y	𝖸	𐘞	Ⲩ	ʏ`,
	"awen": `𝚲	ᐲ	⋏	_^_	⅄	A	Λ`,
	"e": `≫	»	》	>>	⨠`,
	"en": `+	＋	十`,
	"esun": `Ⴥ	𑣥	Z	ꕑ	æ	96`,
	"ijo": `ⵔ	○	O`,
	"ike": `◠	ᴖ	n	⌒`,
	"ilo": `中	𐙩	Ⴔ	T	[]-`,
	"insa": `└ ̇┘	ᕫ	⟓	⨃	[.]	⊡`,
	"jaki": `𖡎	𝟞	96	&`,
	"jan": `𐙞	_O_	.O.	⍜	ჲ	只`,
	"jelo": `ᐂ	🜶	𖡪	Å	/+\\	♗	Δ̊`,
	"jo": `ᕦ	ɕ̊	ჹ	9	ϱ	ջ`,
	"kala": `𑁛	⋊	ᘞ	ю	>o	<><	∝`,
	"kalama": `⏒̋	ᗜ	ᗢ	Ṻ	:D	ᗜ̌	>D`,
	"kama": `𓂻	🝠	Ꮑ	ᐼ	_/\\	λ	l\\`,
	"kasi": `𖧧	ȹ	°l°	ꕚ	-B`,
	"ken": `K	K`,
	"kepeken": `吊	𖣝	ਨ	ꐬ	5-[]	Ⴜ	[]-C`,
	"kili": `⥀	ბ	ద	(')	ర	ථ`,
	"kin": `⸸	ḽ	⤓	*`,
	"kiwen": `⌔	♢	⛉	⬠	\\_/`,
	"ko": `ꕤ	𖧷	♧	ಐ	ణ	c3`,
	"kon": `𐘽	⧚	𐒡𐒡	SS`,
	"kule": `🜁	/-\\`,
	"kulupu": `ஃ	𐬿	🝆	ꖜ	….	:.`,
	"kute": `Ⳋ	ͽ	ᕭ	リ	ᑔ	ॽ	7	੭	ʔ`,
	"la": `)	Ɔ	𐅀	ᑐ`,
	"lape": `⊸	-O	ᓀ	ዑ	O-	⧃`,
	"laso": `Ϫ	ꕨ	l>B`,
	"lawa": `ፁ	⍬	𑴪	θ	⦵	Ø`,
	"len": `𐘮	𝈤	■	用	[ ]E.	F,l`,
	"lete": `Ӿ	＊	*	>l<`,
	"li": `ᐳ	❭	〉	>`,
	"lili": `ᘁ	v	⌄`,
	"linja": `∽	𐅼	~	〜	ᔓ`,
	"lipu": `⎕	□	⌷	[]	囗	[ ]`,
	"loje": `𐃯	Ă	ⴵ	D<l`,
	"lon": `∸	|o	|.	߸`,
	"luka": `ᕄ	ᕆ	ɲ	5	Ꮑ	C,`,
	"lukin": `ᯣ	⦿	ⵙ	<o>`,
	"lupa": `ᑌ	⋃	U`,
	"ma": `ⴲ	⨁	(+)`,
	"mama": `O̥	⧂	Ǫ	8	cO`,
	"mani": `𑀫	🜘	℧	ᗨ	O(	ᴕ`,
	"meli": `⍝	(o	冋`,
	"mi": `ᑭ	P`,
	"mije": `o̪	⍜	Д	O[	Զ	Ջ`,
	"moku": `⩆̄	𐚩	⩆	Ѫ	D-C`,
	"moli": `(xx)	〷	🕀	⨂	¤	ⓧ`,
	"monsi": `‧[	⸡	{	*[	‧ⵎ	ᑡ	-[`,
	"mu": `𖠐	ʘ	̊ ☉ ̊`,
	"mun": `☽	☾	D`,
	"musi": `☋	C8`,
	"mute": `lll	⫴	ꔖ`,
	"namako": `⊹	𖠲	-|-	✛`,
	"nanpa": `ꖛ	⌗	#	ⵌ`,
	"nasa": `౷	൫	@	ᘐ`,
	"nasin": `ᛣ	↑	ᗑ	/|\\`,
	"nena": `∩	⋂	ᑎ	nn	/\\`,
	"ni": `↓	->`,
	"nimi": `ᯆ	[ ]	[]`,
	"noka": `Lᕊ	ᕊ	Ь	lb	lo`,
	"o": `⫰	o	l̥`,
	"oko": `ᗉ	⩹	⪦	<)`,
	"olin": `♡♡	❦	ў	<3<3	🝮	<33`,
	"ona": `ᓄ	ᓀ	\\o	_o`,
	"open": `ㅂ	⩁	𝈣	[-]	Ʉ	-Ll-`,
	"pakala": `⍯	⍗	ϟ	⍄	[\\]	[Z]	Ꮻ`,
	"pali": `ᕅ	ጸ	♬	)O	ጲ	5-O	O-C`,
	"palisa": `꒩	𑃰	⫾	0`,
	"pan": `𐘃	𝅬	>>>	巛	<<<`,
	"pana": `ᣐ	ἤ	):	ᕇ	5<	>C`,
	"pi": `∟	ᒪ`,
	"pilin": `♡	<3`,
	"pimeja": `⨻	/X\\	/x\\`,
	"pini": `ꕯ	𐊈	I	T	工	H`,
	"pipi": `丰	𐀳	‡	.+.	ⴶ	-lll:`,
	"poka": `⊔‧	ᒳ	⎵	[_].	ᑘ	Ll-`,
	"poki": `⊔	⨆	[_]	凵	Ll`,
	"pona": `◡	ᴗ	ᵕ	u`,
	"pu": `⌻	🄿	固	[o]`,
	"sama": `＝	᐀	=	ꘌ`,
	"seli": `ᐠⵑᐟ	ᗐ	':'	\\!/	⩛`,
	"selo": `⺵	ℿ	⟰	lTTl	▥`,
	"seme": `?	ॽ	⍰`,
	"sewi": `ɹɹɺ	⫨	ຝ	wl	ᥘI	Jl	ᎫI	◿`,
	"sijelo": `𐊿	m	[|]	巾	lTl	爪	ጠ/`,
	"sike": `⦾	⌾	(())	◎	(O)`,
	"sin": `-'-	⊥	﬩	_'_	⟂	_l_`,
	"sina": `ᑲ	b	6`,
	"sinpin": `]·	⸠	}	]*	].	ⵎ‧	ᑞ	]-`,
	"sitelen": `ꘖ	[ooo]	[...]	[:]`,
	"sona": `畄	⏍̋	⏍	ṻ	[]:	>[ ]`,
	"soweli": `ıııᕈ	ଲ	☟	m	P	ïᕈ	mP`,
	"suli": `ᐯ	⋎	V`,
	"suno": `🝊	✢	-'o,-	⛭	-|-o`,
	"supa": `ㅠ	𐅺	ᚂ	-,-,-	π	TT	丌`,
	"suwi": `ᶺ.ᶺ	ᨎ	Ṃ	^.^`,
	"tan": `⤺	⟲	<-`,
	"taso": `┤	⫞	-|	˧	|-`,
	"tawa": `𓂽	ሊ	ᐽ	𝈵	/_\\_	/\\_	ʎ	/L`,
	"telo": `≈	NN	ww	ʬ`,
	"tenpo": `◷	Ⓛ	( L )	OL`,
	"toki": `⛣	𖠶	ö	o:	꘠	o<	ǒ`,
	"tomo": `⌂	/\\	l^l`,
	"tonsi": `⚧	Ⓨ	OY`,
	"tu": `॥	𝍪	ll	Ⅱ`,
	"unpa": `ꕢ	Ꮬ	7u7	uwu	owo	8o`,
	"uta": `ᗜ	ụ	D-	Ḍ	D.`,
	"utala": `⤩	ꤸ	\\X/	Ꮤ`,
	"walo": `𐙁	ꕖ	'/\\'	ⴴ	-/ \\-`,
	"wan": `1	↿	˥	ߗ`,
	"waso": `ᔨ	4	∙∙ᔨ	.>`,
	"wawa": `\\o/	⊍	∀	⨃	\\0/`,
	"weka": `∷	⸬	_!_	⛶`,
	"wile": `ω	W	⍵	Ꙍ	ꙍ`,
	"jasima": `⍭	⧧	≉`,
	"kijetesantakalu": `⊂Ꮮıïᔨ	Ⱊ	ഫ`,
	"kipisi": `÷	፥	⸓	%`,
	"kokosila": `⦱	𓆊`,
	"lanpan": `ሮ	ᕔ	ꦌ	ሬ	Lo`,
	"leko": `⧈	[[]]	回`,
	"apeja": `ᵒ%	ポ	ꕣ`,
	"epiku": `ٽ	𐍊	↑`,
	"meso": `|·|	≖	l·l	|.|`,
	"misikeke": `θ	ϴ	(-)`,
	"monsuta": `෴	ʍ	M`,
	"n": `nͥ	ń	l̯	n`,
	"soko": `⍾	=D`,
	"ete": `⏍`,
	"ewe": `⌂`,
	"isipin": `⦵`,
	"kalamARR": `𦬅`,
	"kamalawala": `Ⓐ`,
	"kan": `ߝ`,
	"kapesi": `♗`,
	"ke": `ǩ`,
	"kese": `𝜂`,
	"kiki": `Δ	✷`,
	"likujo": `፨`,
	"oke": `ǒ	☑	✓`,
	"ku": `🄺	◳	[L]`,
	"linluwi": `क`,
	"majuna": `ᗖ`,
	"nimisin": `⏛`,
	"omekapo": `ᘠ`,
	"powe": `⨱`,
	"su": `🅂`,
	"usawi": `ᘕ`,
	"wuwojiti": `⚠`,
	"yupekosi": `📉`,
	"pake": `T	丅`
}

function set_juniko(juniko_text) {
	for (const juniko_p of every_juniko_p) {
		juniko_p.innerHTML = juniko_text;
	}
}

function update_juniko() {
	if (!lasina_box.value) set_juniko("-");

	let juniko_output = "";
	for (const token of lasina_box.value.match(/\w+|[^\w]/g)) { // Thanks chatGPT for the regex :(
		if (token in juniko_list) {
			juniko_output += juniko_list[token].split("\t")[0]
		} else {
			juniko_output += token;
		}
	}
	set_juniko(juniko_output);
}